### ISSUE TITLE
Haxe 4.2.5: set/Set.hx:34: characters 5-26 : error: set.Set.V should be toArray.V

### ISSUE THREAD

**Issue by zommerfelds** [helder/set#9]
Compilation issues on the newest Haxe version. I'll create a proposal PR, but I'm not super familiar with the details of casting and abstract in Haxe, so please double check.

**Comment by zommerfelds** [comment]
Ah never mind, this is already fixed in the latest version. I didn't realize there was more than 0.1.0.

Would it somehow be possible to note this in https://lib.haxe.org/p/set that the library name changed?

**Comment by benmerckx** [comment]
Notice is up, sorry for the confusion!
